/* This file was generated by syncqt. */
#ifndef QT_QT3DLOGIC_VERSION_H
#define QT_QT3DLOGIC_VERSION_H

#define QT3DLOGIC_VERSION_STR "5.5.1"

#define QT3DLOGIC_VERSION 0x050501

#endif // QT_QT3DLOGIC_VERSION_H
