/* This file was generated by syncqt. */
#ifndef QT_QT3DQUICK_VERSION_H
#define QT_QT3DQUICK_VERSION_H

#define QT3DQUICK_VERSION_STR "5.5.1"

#define QT3DQUICK_VERSION 0x050501

#endif // QT_QT3DQUICK_VERSION_H
