/* This file was generated by syncqt. */
#ifndef QT_ACTIVEQT_VERSION_H
#define QT_ACTIVEQT_VERSION_H

#define ACTIVEQT_VERSION_STR "5.5.1"

#define ACTIVEQT_VERSION 0x050501

#endif // QT_ACTIVEQT_VERSION_H
