/* This file was generated by syncqt. */
#ifndef QT_QT3DINPUT_VERSION_H
#define QT_QT3DINPUT_VERSION_H

#define QT3DINPUT_VERSION_STR "5.5.1"

#define QT3DINPUT_VERSION 0x050501

#endif // QT_QT3DINPUT_VERSION_H
